apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  default.conf.template: |
    # Instana tracing
    opentracing_load_tracer /usr/local/lib/libinstana_sensor.so /etc/instana-config.json;
    opentracing_propagate_context;

    server {
        listen       8080;
        server_name  localhost;

        proxy_http_version 1.1;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            ssi    on;
        }

        location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.png;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # ----------------------------
        # Backend service proxies
        # ----------------------------

        location /api/catalogue/ {
            proxy_pass http://${CATALOGUE_HOST}:8080/;
        }

        location /api/user/ {
            proxy_pass http://${USER_HOST}:8080/;
        }

        location /api/cart/ {
            proxy_pass http://${CART_HOST}:8080/;
        }

        location /api/shipping/ {
            proxy_pass http://${SHIPPING_HOST}:8080/;
        }

        location /api/payment/ {
            proxy_pass http://${PAYMENT_HOST}:8080/;
        }

        location /api/ratings/ {
            proxy_pass http://${RATINGS_HOST}:80/;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
        }
    }
